In [1]:
import pandas as pd
import numpy as np
import os
import datetime as dt

In [2]:
f1 = open("/Users/shreyassrinivasan/Desktop/SF_Project_Alias/flightData.csv")
df1 = pd.read_csv(f1)

In [3]:
f2 = open("/Users/shreyassrinivasan/Desktop/SF_Project_Alias/WeatherData.csv")
df2 = pd.read_csv(f2)

In [4]:
df1

,Unnamed: 0,Year,Quarter,Month,DayofMonth,FlightDate,OriginAirportID,Origin,DestAirportID,Dest,CRSDepTime,DepTime,DepDelayMinutes,DepDel15,CRSArrTime,ArrTime,ArrDelayMinutes,ArrDel15
0,0,2016,4,12,1,2016-12-01,13204,MCO,13930,ORD,1400,1404.0,4.0,0.0,1601,1554.0,0.0,0.0
1,1,2016,4,12,2,2016-12-02,13204,MCO,13930,ORD,1400,1410.0,10.0,0.0,1601,1602.0,1.0,0.0
2,2,2016,4,12,3,2016-12-03,13204,MCO,13930,ORD,1400,1351.0,0.0,0.0,1601,1534.0,0.0,0.0
3,3,2016,4,12,4,2016-12-04,13204,MCO,13930,ORD,1400,1603.0,123.0,1.0,1601,1809.0,128.0,1.0
4,4,2016,4,12,5,2016-12-05,13204,MCO,13930,ORD,1400,1402.0,2.0,0.0,1601,1557.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1877291,1877291,2017,1,2,7,2017-02-07,11618,EWR,11292,DEN,1745,1737.0,0.0,0.0,2005,1951.0,0.0,0.0
1877292,1877292,2017,1,2,7,2017-02-07,11618,EWR,11292,DEN,1300,1257.0,0.0,0.0,1520,1530.0,10.0,0.0
1877293,1877293,2017,1,2,7,2017-02-07,11618,EWR,13204,MCO,600,635.0,35.0,1.0,905,911.0,6.0,0.0
1877294,1877294,2017,1,2,7,2017-02-07,11618,EWR,13204,MCO,1345,1353.0,8.0,0.0,1645,1638.0,0.0,0.0
1877295,1877295,2017,1,2,7,2017-02-07,11618,EWR,14107,PHX,1520,1516.0,0.0,0.0,1850,1843.0,0.0,0.0

In [5]:
df2

,Unnamed: 0,windspeedKmph,winddirDegree,weatherCode,precipMM,visibility,pressure,cloudcover,DewPointF,WindGustKmph,tempF,WindChillF,humidity,date,time,airport
0,0,10,209,122,0.0,10,1012,99,60,14,63,63,90,2016-02-01,0,IAH
1,1,8,209,122,0.0,10,1012,99,60,11,63,63,90,2016-02-01,100,IAH
2,2,6,209,122,0.0,10,1012,100,60,9,63,63,90,2016-02-01,200,IAH
3,3,5,209,122,0.1,10,1012,100,60,6,63,63,90,2016-02-01,300,IAH
4,4,5,195,122,0.1,10,1012,100,60,6,62,62,90,2016-02-01,400,IAH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263155,263155,19,110,113,0.0,10,1018,0,74,22,87,87,65,2017-05-31,1900,MIA
263156,263156,18,110,113,0.0,10,1018,0,74,21,86,86,67,2017-05-31,2000,MIA
263157,263157,17,110,113,0.0,10,1018,0,74,20,85,85,69,2017-05-31,2100,MIA
263158,263158,15,113,113,0.0,10,1018,8,73,19,84,84,70,2017-05-31,2200,MIA
263159,263159,14,116,119,0.0,10,1018,15,73,18,84,84,70,2017-05-31,2300,MIA

In [6]:
df1['ArrFlightDate'] = df1['FlightDate']
df1['ArrFlightDate'] = pd.to_datetime(df1['ArrFlightDate'])
df1['FlightDate'] = pd.to_datetime(df1['FlightDate'])

In [7]:
df1['ArrAbsTime'] = df1['CRSArrTime']
for index, row in df1.iterrows():
    remainder = row["ArrAbsTime"]%100
    absoluteTime = row["ArrAbsTime"] - remainder
    df1.at[index,"ArrAbsTime"] = absoluteTime
    if(row["CRSDepTime"] > row["CRSArrTime"]):
        df1.at[index,"ArrFlightDate"] = row["FlightDate"] + pd.DateOffset(days=1)

In [8]:
df1['ArrAbsTime'] = df1['ArrAbsTime'].astype(np.int64)

In [9]:
for index,row in df1.iterrows():
    if(row["CRSArrTime"]==2400):
        df1.at[index,"CRSArrTime"]=0
        df1.at[index,"ArrAbsTime"]=0

In [10]:
df1["DepAbsTime"] = df1["CRSDepTime"]
for index, row in df1.iterrows():
    remainder = row["DepAbsTime"]%100
    absolutetime = row["DepAbsTime"] - remainder
    df1.at[index,"DepAbsTime"] = absolutetime

In [11]:
df1['DepAbsTime'] = df1['DepAbsTime'].astype(np.int64)

In [14]:
df1.transpose()

,0,1,2,3,4,5,6,7,8,9,...,1877286,1877287,1877288,1877289,1877290,1877291,1877292,1877293,1877294,1877295
Unnamed: 0,0,1,2,3,4,5,6,7,8,9,...,1877286,1877287,1877288,1877289,1877290,1877291,1877292,1877293,1877294,1877295
Year,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016,...,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017
Quarter,4,4,4,4,4,4,4,4,4,4,...,1,1,1,1,1,1,1,1,1,1
Month,12,12,12,12,12,12,12,12,12,12,...,2,2,2,2,2,2,2,2,2,2
DayofMonth,1,2,3,4,5,6,7,8,9,10,...,7,7,7,7,7,7,7,7,7,7
FlightDate,2016-12-01 00:00:00,2016-12-02 00:00:00,2016-12-03 00:00:00,2016-12-04 00:00:00,2016-12-05 00:00:00,2016-12-06 00:00:00,2016-12-07 00:00:00,2016-12-08 00:00:00,2016-12-09 00:00:00,2016-12-10 00:00:00,...,2017-02-07 00:00:00,2017-02-07 00:00:00,2017-02-07 00:00:00,2017-02-07 00:00:00,2017-02-07 00:00:00,2017-02-07 00:00:00,2017-02-07 00:00:00,2017-02-07 00:00:00,2017-02-07 00:00:00,2017-02-07 00:00:00
OriginAirportID,13204,13204,13204,13204,13204,13204,13204,13204,13204,13204,...,11292,11292,11292,11292,11618,11618,11618,11618,11618,11618
Origin,MCO,MCO,MCO,MCO,MCO,MCO,MCO,MCO,MCO,MCO,...,DEN,DEN,DEN,DEN,EWR,EWR,EWR,EWR,EWR,EWR
DestAirportID,13930,13930,13930,13930,13930,13930,13930,13930,13930,13930,...,14771,14771,14771,14771,11292,11292,11292,13204,13204,14107
Dest,ORD,ORD,ORD,ORD,ORD,ORD,ORD,ORD,ORD,ORD,...,SFO,SFO,SFO,SFO,DEN,DEN,DEN,MCO,MCO,PHX
CRSDepTime,1400,1400,1400,1400,1400,1400,1400,1400,1400,1400,...,2140,840,1915,1215,810,1745,1300,600,1345,1520
DepTime,1404,1410,1351,1603,1402,1453,1401,1413,1358,1400,...,2137,839,1949,1228,807,1737,1257,635,1353,1516
DepDelayMinutes,4,10,0,123,2,53,1,13,0,0,...,0,0,34,13,0,0,0,35,8,0
DepDel15,0,0,0,1,0,1,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
CRSArrTime,1601,1601,1601,1601,1601,1601,1601,1601,1601,1601,...,2325,1020,2055,1355,1035,2005,1520,905,1645,1850
ArrTime,1554,1602,1534,1809,1557,1637,1651,1601,1608,1541,...,2332,1043,2156,1442,1028,1951,1530,911,1638,1843
ArrDelayMinutes,0,1,0,128,0,36,50,0,7,0,...,7,23,61,47,0,0,10,6,0,0
ArrDel15,0,0,0,1,0,1,1,0,0,0,...,0,1,1,1,0,0,0,0,0,0
ArrFlightDate,2016-12-01 00:00:00,2016-12-02 00:00:00,2016-12-03 00:00:00,2016-12-04 00:00:00,2016-12-05 00:00:00,2016-12-06 00:00:00,2016-12-07 00:00:00,2016-12-08 00:00:00,2016-12-09 00:00:00,2016-12-10 00:00:00,...,2017-02-07 00:00:00,2017-02-07 00:00:00,2017-02-07 00:00:00,2017-02-07 00:00:00,2017-02-07 00:00:00,2017-02-07 00:00:00,2017-02-07 00:00:00,2017-02-07 00:00:00,2017-02-07 00:00:00,2017-02-07 00:00:00
ArrAbsTime,1600,1600,1600,1600,1600,1600,1600,1600,1600,1600,...,2300,1000,2000,1300,1000,2000,1500,900,1600,1800
DepAbsTime,1400,1400,1400,1400,1400,1400,1400,1400,1400,1400,...,2100,800,1900,1200,800,1700,1300,600,1300,1500

In [17]:
df2.date = pd.to_datetime(df2.date)

In [18]:
df2

,Unnamed: 0,windspeedKmph,winddirDegree,weatherCode,precipMM,visibility,pressure,cloudcover,DewPointF,WindGustKmph,tempF,WindChillF,humidity,date,time,airport
0,0,10,209,122,0.0,10,1012,99,60,14,63,63,90,2016-02-01,0,IAH
1,1,8,209,122,0.0,10,1012,99,60,11,63,63,90,2016-02-01,100,IAH
2,2,6,209,122,0.0,10,1012,100,60,9,63,63,90,2016-02-01,200,IAH
3,3,5,209,122,0.1,10,1012,100,60,6,63,63,90,2016-02-01,300,IAH
4,4,5,195,122,0.1,10,1012,100,60,6,62,62,90,2016-02-01,400,IAH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263155,263155,19,110,113,0.0,10,1018,0,74,22,87,87,65,2017-05-31,1900,MIA
263156,263156,18,110,113,0.0,10,1018,0,74,21,86,86,67,2017-05-31,2000,MIA
263157,263157,17,110,113,0.0,10,1018,0,74,20,85,85,69,2017-05-31,2100,MIA
263158,263158,15,113,113,0.0,10,1018,8,73,19,84,84,70,2017-05-31,2200,MIA
263159,263159,14,116,119,0.0,10,1018,15,73,18,84,84,70,2017-05-31,2300,MIA

In [19]:
merge1 = df1.merge(df2,left_on=["FlightDate","DepAbsTime","Origin"],right_on=["date","time","airport"])

In [20]:
merge2 = merge1.merge(df2,left_on=["ArrFlightDate","ArrAbsTime","Dest"],right_on=["date","time","airport"])

In [21]:
merge2

,Unnamed: 0_x,Year,Quarter,Month,DayofMonth,FlightDate,OriginAirportID,Origin,DestAirportID,Dest,...,pressure_y,cloudcover_y,DewPointF_y,WindGustKmph_y,tempF_y,WindChillF_y,humidity_y,date_y,time_y,airport_y
0,0,2016,4,12,1,2016-12-01,13204,MCO,13930,ORD,...,1012,97,34,30,41,33,79,2016-12-01,1600,ORD
1,9276,2016,4,12,1,2016-12-01,13303,MIA,13930,ORD,...,1012,97,34,30,41,33,79,2016-12-01,1600,ORD
2,31142,2016,4,12,1,2016-12-01,12892,LAX,13930,ORD,...,1012,97,34,30,41,33,79,2016-12-01,1600,ORD
3,60799,2016,4,12,1,2016-12-01,14771,SFO,13930,ORD,...,1012,97,34,30,41,33,79,2016-12-01,1600,ORD
4,19650,2016,4,12,1,2016-12-01,11292,DEN,13930,ORD,...,1012,97,34,30,41,33,79,2016-12-01,1600,ORD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1877189,1871552,2017,1,2,25,2017-02-25,11298,DFW,14107,PHX,...,1014,100,32,10,57,57,39,2017-02-26,0,PHX
1877190,1872680,2017,1,2,19,2017-02-19,12889,LAS,12892,LAX,...,1010,100,51,5,52,52,95,2017-02-19,600,LAX
1877191,1874517,2017,1,2,18,2017-02-18,12889,LAS,12892,LAX,...,1000,100,50,32,53,49,92,2017-02-18,600,LAX
1877192,1876423,2017,1,2,25,2017-02-25,12889,LAS,12892,LAX,...,1020,36,45,13,47,45,93,2017-02-25,600,LAX
1877193,1876621,2017,1,2,26,2017-02-26,12889,LAS,12892,LAX,...,1016,90,47,5,52,52,85,2017-02-26,600,LAX

In [22]:
#merge2.to_csv('/Users/shreyassrinivasan/Desktop/SF_Project_Alias/merge_final.csv')